# Generated by Django 4.2.7 on 2023-12-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('price', models.CharField(default='1', max_length=120)),
                ('quantity', models.CharField(default='1', max_length=120)),
                ('order_date', models.DateTimeField(default='', max_length=120)),
                ('isAvailable', models.CharField(default='true', max_length=120)),
            ],
        ),
    ]
