# Generated by Django 4.2.7 on 2023-12-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.IntegerField(default=-1),
        ),
    ]
