# Generated by Django 4.2.7 on 2023-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerId',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isAvailable',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default='', max_length=120),
        ),
    ]
