# Generated by Django 4.2.7 on 2023-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_customerid_order_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_available',
            field=models.CharField(default=True, max_length=5),
        ),
    ]
