# Generated by Django 4.2.7 on 2023-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('address', models.TextField(default='')),
                ('phoneNumber', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
